project:
  type: website
  post-render:
    - quarto run copy_files_site.ts 
    - node inject_service_worker_manifest.js
  preview:
    # host: 0.0.0.0
    port: 4100
    browser: false

website:
  favicon: files/images/app_icon/icon.jpg
  title: SuperInfo
  search: true
  page-navigation: true
  navbar:
    pinned: false
    title: SuperInfo 
    right:
      - icon: instagram
        href: https://instagram.com/rede_de_educacao_e_saude_
      - icon: youtube
        href: https://www.youtube.com/@RedeEducacaoeSaudeemEscolasPub
  sidebar: 
    style: "docked"
    search: true
    contents: conteudo/**/*
  page-footer:
    background: "#2595b4"
    foreground: "#ffffff"
    border: false
    left:
      - text: Página inicial
        href: index.qmd
      - text: Sobre
        href: sobre.qmd
      # - text: Instagram
      #   href: https://instagram.com/rede_de_educacao_e_saude_
      # - text: Youtube
      #   href: https://www.youtube.com/@RedeEducacaoeSaudeemEscolasPub
      
    right:
      - text: "Realização:"
      - icon: gov 
        href: https://www.gov.br/cnpq/pt-br
      - icon: ufrb
        href: https://www.ufrb.edu.br
      - icon: ifba
        href: https://portal.ifba.edu.br/
      
     

format:
  html:
    include-in-header:
      - text: |
          <link rel="manifest" href="/files/manifest.json">
    include-after-body: 
      - text: <script type="module" src="/files/scripts/toggle_sidebar_script.js "></script> 
      - text: <script type="module" src="/files/scripts/loadserviceworker.js "></script> 
    grid: 
      body-width: 1275px
    toc: false
    echo: false
    keep-hidden: true
    smooth-scroll: true
    theme:
      - zephyr
      - custom.scss
      
    css: styles.css



