project:
  type: website
  post-render:
    - quarto run copy_files_site.ts 
    - node inject_service_worker_manifest.js
  preview:
    # host: 0.0.0.0
    port: 4100
    browser: false

website:
  favicon: files/images/app_icon/icon.jpg
  title: SuperInfo
  search: true
  page-navigation: true
  navbar:
    pinned: false
    title: SuperInfo 
    right:
      - icon: instagram
        href: https://instagram.com/rede_de_educacao_e_saude_
      - icon: youtube
        href: https://www.youtube.com/@RedeEducacaoeSaudeemEscolasPub
  sidebar: 
    pinned: false
    border: false
    align: center
    style: floating
    collapse-level: 1
    contents:
      - href: index.qmd
        text: <i class="bi bi-house"></i> Página inicial
      - section: <i class="bi bi-backpack"></i> ENEM
        contents: 
        - href: conteudo/enem/sobre.qmd
          text:  O que é o ENEM 
        - href: conteudo/enem/inscricao.qmd
          text: Inscrição
        - section: Como funciona a prova
          contents:
            - href: conteudo/enem/como_funciona/estrutura.qmd
              text: Estrutura
            - href: conteudo/enem/como_funciona/tipos_de_questoes.qmd
              text: Tipos de questões
        - section: O que estudar
          contents:
            - href: conteudo/enem/o_que_estudar/conteudos.qmd
              text: Conteúdos
            - href: conteudo/enem/o_que_estudar/dicas_de_preparacao.qmd
              text: Dicas de preparação
        - href: conteudo/enem/como_utilizar_a_nota.qmd
          text: Como utilizar a nota do ENEM        
      - section: <i class="bi bi-piggy-bank"></i> SISU
        contents: 
        - href: conteudo/sisu/sobre.qmd
          text: O que é o SISU
        - href: conteudo/sisu/quem_pode_participar.qmd
          text: Quem pode participar
        - section: Inscrição
          contents:
            - href: conteudo/sisu/inscricao/como_se_inscrever.qmd
              text: Como se inscrever
            - href: conteudo/sisu/inscricao/prazos_importantes.qmd
              text: Prazos importantes
        - href: conteudo/sisu/processo_de_selecao.qmd
          text: Processo de seleção
      - section: <i class="bi bi-globe"></i> Direitos dos estudantes
        contents:
          - href: conteudo/direitos/quais_sao.qmd
            text: Quais são
          - section: Políticas estudantis
            contents:
              - href: conteudo/direitos/politicas_de_permanencia_estudantil/bolsas.qmd
                text: Bolsas
              - href: conteudo/direitos/politicas_de_permanencia_estudantil/moradia.qmd
                text: Moradia
              - href: conteudo/direitos/politicas_de_permanencia_estudantil/alimentacao.qmd
                text: Alimentação
          - section: Situações de avaliação
            contents:
              - href: conteudo/direitos/situacoes_de_avaliacao/revisao_de_provas.qmd
                text: Revisão de Provas
              - href: conteudo/direitos/situacoes_de_avaliacao/entrada_de_recursos_academicos.qmd
                text: Recursos acadêmicos
          - section: Ambito acadêmico
            contents:
              - href: conteudo/direitos/ambito_academico/garantia_de_educacao_de_qualidade.qmd
                text: Educação de qualidade
              - href: conteudo/direitos/ambito_academico/inclusao_de_pessoas_com_deficiencia.qmd
                text: Inclusão
          - section: Atividade para os estudantes
            contents:
              - section: Grupos de pesquisa
                contents:
                  - href: conteudo/atividades/grupos_de_pesquisa/iniciacao_cientifica.qmd
                    text: Iniciação científica
              - href: conteudo/atividades/eventos_academicos.qmd
                text: Eventos acadêmicos
              - href: conteudo/atividades/intercambio_academico.qmd
                text: Intercâmbio acadêmico
              - href: conteudo/atividades/monitoria.qmd
                text: Monitoria
  page-footer:
    background: "#2595b4"
    foreground: "#ffffff"
    border: false
    left:
      - text: Página inicial
        href: index.qmd
      - text: Sobre
        href: sobre.qmd
      # - text: Instagram
      #   href: https://instagram.com/rede_de_educacao_e_saude_
      # - text: Youtube
      #   href: https://www.youtube.com/@RedeEducacaoeSaudeemEscolasPub
      
    right:
      - text: "Realização:"
      - icon: gov 
        href: https://www.gov.br/cnpq/pt-br
      - icon: ufrb
        href: https://www.ufrb.edu.br
      - icon: ifba
        href: https://portal.ifba.edu.br/
      
     

format:
  html:
    include-in-header:
      - text: |
          <link rel="manifest" href="/files/manifest.json">
    include-after-body: 
      - text: <script type="module" src="/files/scripts/toggle_sidebar_script.js "></script> 
      - text: <script type="module" src="/files/scripts/loadserviceworker.js "></script> 
    grid: 
      body-width: 1275px
    toc: false
    echo: false
    keep-hidden: true
    smooth-scroll: true
    theme:
      - zephyr
      - custom.scss
      
    css: styles.css



